export const listUniversity = [
    "INSTITUT PERTANIAN BOGOR",
    "INSTITUT TEKNOLOGI BANDUNG",
    "INSTITUT TEKNOLOGI KALIMANTAN",
    "INSTITUT TEKNOLOGI SEPULUH NOPEMBER",
    "INSTITUT TEKNOLOGI SUMATERA",
    "ISBI ACEH",
    "ISBI BANDUNG",
    "ISBI TANAH PAPUA",
    "ISI DENPASAR",
    "ISI PADANG PANJANG",
    "ISI SURAKARTA",
    "ISI YOGYAKARTA",
    "UNIVERSITAS AIRLANGGA",
    "UNIVERSITAS ANDALAS",
    "UNIVERSITAS BANGKA BELITUNG",
    "UNIVERSITAS BENGKULU",
    "UNIVERSITAS BORNEO TARAKAN",
    "UNIVERSITAS BRAWIJAYA",
    "UNIVERSITAS CENDERAWASIH",
    "UNIVERSITAS DIPONEGORO",
    "UNIVERSITAS GADJAH MADA",
    "UNIVERSITAS HALUOLEO",
    "UNIVERSITAS HASANUDDIN",
    "UNIVERSITAS INDONESIA",
    "UNIVERSITAS ISLAM NEGERI ALAUDDIN",
    "UNIVERSITAS ISLAM NEGERI AR-RANIRY",
    "UNIVERSITAS ISLAM NEGERI JAKARTA",
    "UNIVERSITAS ISLAM NEGERI MALANG",
    "UNIVERSITAS ISLAM NEGERI RADEN FATAH",
    "UNIVERSITAS ISLAM NEGERI SULTAN SYARIF KASIM",
    "UNIVERSITAS ISLAM NEGERI SUMATERA UTARA",
    "UNIVERSITAS ISLAM NEGERI SUNAN AMPEL SURABAYA",
    "UNIVERSITAS ISLAM NEGERI SUNAN GUNUNG DJATI",
    "UNIVERSITAS ISLAM NEGERI SUNAN KALIJAGA",
    "UNIVERSITAS ISLAM NEGERI WALISONGO",
    "UNIVERSITAS JAMBI",
    "UNIVERSITAS JEMBER",
    "UNIVERSITAS JENDERAL SOEDIRMAN",
    "UNIVERSITAS KHAIRUN",
    "UNIVERSITAS LAMBUNG MANGKURAT",
    "UNIVERSITAS LAMPUNG",
    "UNIVERSITAS MALIKUSSALEH",
    "UNIVERSITAS MARITIM RAJA ALI HAJI",
    "UNIVERSITAS MATARAM",
    "UNIVERSITAS MULAWARMAN",
    "UNIVERSITAS MUSAMUS MERAUKE",
    "UNIVERSITAS NEGERI GORONTALO",
    "UNIVERSITAS NEGERI JAKARTA",
    "UNIVERSITAS NEGERI MAKASSAR",
    "UNIVERSITAS NEGERI MALANG",
    "UNIVERSITAS NEGERI MANADO",
    "UNIVERSITAS NEGERI MEDAN",
    "UNIVERSITAS NEGERI PADANG",
    "UNIVERSITAS NEGERI SEMARANG",
    "UNIVERSITAS NEGERI SURABAYA",
    "UNIVERSITAS NEGERI YOGYAKARTA",
    "UNIVERSITAS NUSA CENDANA",
    "UNIVERSITAS PADJADJARAN",
    "UNIVERSITAS PALANGKARAYA",
    "UNIVERSITAS PAPUA",
    "UNIVERSITAS PATTIMURA",
    "UNIVERSITAS PENDIDIKAN GANESHA",
    "UNIVERSITAS PENDIDIKAN INDONESIA",
    "UNIVERSITAS RIAU",
    "UNIVERSITAS SAM RATULANGI",
    "UNIVERSITAS SAMUDRA",
    "UNIVERSITAS SEBELAS MARET",
    "UNIVERSITAS SEMBILAN BELAS NOVEMBER KOLAKA",
    "UNIVERSITAS SILIWANGI",
    "UNIVERSITAS SINGAPERBANGSA KARAWANG",
    "UNIVERSITAS SRIWIJAYA",
    "UNIVERSITAS SULAWESI BARAT",
    "UNIVERSITAS SULTAN AGENG TIRTAYASA",
    "UNIVERSITAS SUMATERA UTARA",
    "UNIVERSITAS SYIAH KUALA",
    "UNIVERSITAS TADULAKO",
    "UNIVERSITAS TANJUNGPURA",
    "UNIVERSITAS TEUKU UMAR",
    "UNIVERSITAS TIDAR",
    "UNIVERSITAS TIMOR",
    "UNIVERSITAS TRUNOJOYO MADURA",
    "UNIVERSITAS UDAYANA",
    "UPN \"VETERAN\" JAKARTA",
    "UPN \"VETERAN\" JAWA TIMUR",
    "UPN \"VETERAN\" YOGYAKARTA",
]

export const listProdi = {
    "UNIVERSITAS SYIAH KUALA": {
        Saintek: [
            "PENDIDIKAN DOKTER HEWAN",
            "TEKNIK SIPIL",
            "TEKNIK MESIN",
            "TEKNIK KIMIA",
            "ARSITEKTUR",
            "TEKNIK ELEKTRO",
            "AGROTEKNOLOGI",
            "AGRIBISNIS",
            "PETERNAKAN",
            "TEKNOLOGI HASIL PERTANIAN",
            "TEKNIK PERTANIAN",
            "PENDIDIKAN BIOLOGI",
            "PENDIDIKAN MATEMATIKA",
            "PENDIDIKAN FISIKA",
            "PENDIDIKAN KIMIA",
            "PENDIDIKAN DOKTER",
            "ILMU KEPERAWATAN",
            "PENDIDIKAN DOKTER GIGI",
            "MATEMATIKA",
            "FISIKA",
            "KIMIA",
            "BIOLOGI",
            "ILMU KELAUTAN",
            "BUDIDAYA PERAIRAN",
            "TEKNIK INDUSTRI",
            "INFORMATIKA",
            "FARMASI",
            "TEKNIK GEOFISIKA",
            "TEKNIK PERTAMBANGAN",
            "STATISTIKA",
            "PEMANFAATAN SUMBERDAYA PERIKANAN",
            "ILMU TANAH",
            "TEKNIK GEOLOGI",
            "AGROTEKNOLOGI (PSDKU GAYO LUES)",
            "PENDIDIKAN BIOLOGI (PDSKU GAYO LUES)",
            "KEHUTANAN (PSDKU GAYO LUES)",
            "PROTEKSI TANAMAN",
            "PERENCANAAN WILAYAH DAN KOTA",
            "KEHUTANAN",
            "TEKNIK KOMPUTER",
        ],
        Soshum: [
            "EKONOMI PEMBANGUNAN",
            "MANAJEMEN",
            "AKUNTANSI",
            "ILMU HUKUM",
            "PENDIDIKAN PANCASILA DAN KEWARGANEGARAAN",
            "PENDIDIKAN SEJARAH",
            "PENDIDIKAN EKONOMI",
            "PENDIDIKAN GEOGRAFI",
            "PENDIDIKAN BAHASA INDONESIA",
            "PENDIDIKAN BAHASA INGGRIS",
            "PENDIDIKAN SENI DRAMA TARI DAN MUSIK",
            "PENDIDIKAN KESEJAHTERAAN KELUARGA",
            "PEND. JASMANI KESEHATAN DAN REKREASI",
            "BIMBINGAN KONSELING",
            "PENDIDIKAN GURU SEKOLAH DASAR",
            "PSIKOLOGI",
            "ILMU POLITIK",
            "SOSIOLOGI",
            "ILMU KOMUNIKASI",
            "PENDIDIKAN GURU PAUD",
            "ILMU PEMERINTAHAN",
            "EKONOMI ISLAM",
            "MANAJEMEN (PSDKU GAYO LUES)",
        ]
    },
    "UNIVERSITAS MALIKUSSALEH": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS TEUKU UMAR": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS SAMUDRA": {
        Saintek: [],
        Soshum: []
    },
    "ISBI ACEH": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ISLAM NEGERI AR-RANIRY": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS SUMATERA UTARA": {
        Saintek: [
            "AGRIBISNIS",
            "AGROEKOTEKNOLOGI",
            "ARSITEKTUR",
            "BIOLOGI",
            "FARMASI",
            "FISIKA",
            "ILMU DAN TEKNOLOGI PANGAN",
            "ILMU KEPERAWATAN",
            "ILMU KESEHATAN MASYARAKAT",
            "ILMU KOMPUTER",
            "KEHUTANAN",
            "KETEKNIKAN PERTANIAN",
            "KIMIA",
            "MANAJEMEN SUMBER DAYA PERAIRAN",
            "MATEMATIKA",
            "PENDIDIKAN DOKTER",
            "PENDIDIKAN DOKTER GIGI",
            "PETERNAKAN",
            "TEKNIK ELEKTRO",
            "TEKNIK INDUSTRI",
            "TEKNIK KIMIA",
            "TEKNIK LINGKUNGAN",
            "TEKNIK MESIN",
            "TEKNIK SIPIL",
            "TEKNOLOGI INFORMASI",
        ],
        Soshum: [
            "AKUNTANSI",
            "ANTROPOLOGI SOSIAL",
            "EKONOMI PEMBANGUNAN",
            "ETNO MUSIKOLOGI",
            "ILMU ADMINISTRASI NEGARA",
            "ILMU ADMINISTRASI NIAGA/BISNIS",
            "ILMU HUKUM",
            "ILMU KESEJAHTERAAN SOSIAL",
            "ILMU KOMUNIKASI",
            "ILMU PERPUSTAKAAN",
            "ILMU POLITIK",
            "ILMU SEJARAH",
            "MANAJEMEN",
            "PSIKOLOGI",
            "SASTRA ARAB",
            "SASTRA CINA",
            "SASTRA DAERAH UNTUK SASTRA BATAK",
            "SASTRA DAERAH UNTUK SASTRA MELAYU",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
            "SASTRA JEPANG",
            "SOSIOLOGI",
        ]
    },
    "UNIVERSITAS NEGERI MEDAN": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ISLAM NEGERI SUMATERA UTARA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS RIAU": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ISLAM NEGERI SULTAN SYARIF KASIM": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS MARITIM RAJA ALI HAJI": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ANDALAS": {
        Saintek: [
            "AGRIBISNIS",
            "AGROEKOTEKNOLOGI",
            "AGROTEKNOLOGI",
            "BIOLOGI",
            "FARMASI",
            "FISIKA",
            "GIZI",
            "ILMU BIOMEDIS",
            "ILMU TANAH",
            "KEBIDANAN",
            "KEDOKTERAN",
            "KEDOKTERAN GIGI",
            "KEPERAWATAN",
            "KESEHATAN MASYARAKAT",
            "KIMIA",
            "MATEMATIKA",
            "PENYULUHAN PERTANIAN",
            "PETERNAKAN",
            "PETERNAKAN ( KAMPUS II PAYAKUMBUH)",
            "PROTEKSI TANAMAN",
            "PSIKOLOGI",
            "SISTEM INFORMASI",
            "TEKNIK ELEKTRO",
            "TEKNIK INDUSTRI",
            "TEKNIK KOMPUTER",
            "TEKNIK LINGKUNGAN",
            "TEKNIK MESIN",
            "TEKNIK PERTANIAN DAN BIOSISTEM",
            "TEKNIK SIPIL",
            "TEKNOLOGI HASIL PERTANIAN",
            "TEKNOLOGI INDUSTRI PERTANIAN",
        ],
        Soshum: [
            "ADMINISTRASI PUBLIK",
            "AKUNTANSI",
            "ANTROPOLOGI SOSIAL",
            "EKONOMI",
            "EKONOMI (KAMPUS 2 PAYAKUMBUH)",
            "HUBUNGAN INTERNASIONAL",
            "HUKUM",
            "ILMU KOMUNIKASI",
            "ILMU POLITIK",
            "MANAJEMEN",
            "MANAJEMEN (KAMPUS 2 PAYAKUMBUH)",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
            "SASTRA JEPANG",
            "SASTRA MINANGKABAU",
            "SEJARAH",
            "SOSIOLOGI",
        ]
    },
    "UNIVERSITAS NEGERI PADANG": {
        Saintek: [],
        Soshum: []
    },
    "ISI PADANG PANJANG": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS JAMBI": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS BENGKULU": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS SRIWIJAYA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ISLAM NEGERI RADEN FATAH": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS BANGKA BELITUNG": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS LAMPUNG": {
        Saintek: [],
        Soshum: []
    },
    "INSTITUT TEKNOLOGI SUMATERA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS SULTAN AGENG TIRTAYASA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS INDONESIA": {
        Saintek: [
            "AKTUARIA",
            "ARSITEKTUR",
            "ARSITEKTUR INTERIOR",
            "BIOLOGI",
            "FARMASI",
            "FISIKA",
            "GEOFISIKA",
            "GEOGRAFI",
            "GEOLOGI",
            "GIZI",
            "ILMU KEPERAWATAN",
            "ILMU KESEHATAN MASYARAKAT",
            "ILMU KOMPUTER",
            "KESEHATAN LINGKUNGAN",
            "KESELAMATAN DAN KESEHATAN KERJA",
            "KIMIA",
            "MATEMATIKA",
            "PENDIDIKAN DOKTER",
            "PENDIDIKAN DOKTER GIGI",
            "SISTEM INFORMASI",
            "STATISTIKA",
            "TEKNIK BIOMEDIS",
            "TEKNIK ELEKTRO",
            "TEKNIK INDUSTRI",
            "TEKNIK KIMIA",
            "TEKNIK KOMPUTER",
            "TEKNIK LINGKUNGAN",
            "TEKNIK MESIN",
            "TEKNIK METALURGI & MATERIAL",
            "TEKNIK PERKAPALAN",
            "TEKNIK SIPIL",
            "TEKNOLOGI BIOPROSES",
        ],
        Soshum: [
            "AKUNTANSI",
            "ANTROPOLOGI SOSIAL",
            "ARKEOLOGI INDONESIA",
            "BAHASA DAN KEBUDAYAAN KOREA",
            "BISNIS ISLAM",
            "ILMU ADMINISTRASI FISKAL",
            "ILMU ADMINISTRASI NEGARA",
            "ILMU ADMINISTRASI NIAGA",
            "ILMU EKONOMI",
            "ILMU EKONOMI ISLAM",
            "ILMU FILSAFAT",
            "ILMU HUBUNGAN INTERNASIONAL",
            "ILMU HUKUM",
            "ILMU KESEJAHTERAAN SOSIAL",
            "ILMU KOMUNIKASI",
            "ILMU PERPUSTAKAAN",
            "ILMU POLITIK",
            "ILMU PSIKOLOGI",
            "ILMU SEJARAH",
            "KRIMINOLOGI",
            "MANAJEMEN",
            "SASTRA ARAB",
            "SASTRA BELANDA",
            "SASTRA CINA",
            "SASTRA DAERAH UNTUK SASTRA JAWA",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
            "SASTRA JEPANG",
            "SASTRA JERMAN",
            "SASTRA PERANCIS",
            "SASTRA RUSIA",
            "SOSIOLOGI",
        ]
    },
    "UNIVERSITAS ISLAM NEGERI JAKARTA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS NEGERI JAKARTA": {
        Saintek: [],
        Soshum: []
    },
    "UPN \"VETERAN\" JAKARTA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS SINGAPERBANGSA KARAWANG": {
        Saintek: [],
        Soshum: []
    },
    "INSTITUT TEKNOLOGI BANDUNG": {
        Saintek: [
            "FAK. ILMU DAN TEKNOLOGI KEBUMIAN (FITB)",
            "FAK. MATEMATIKA & ILMU PENGET. ALAM (FMIPA)",
            "FAK. TEKNIK PERTAMB. & PERMINYAKAN (FTTM)",
            "FAK. TEKNIK PERTAMB. & PERMINYAKAN (FTTM) - KAMPUS CIREBON",
            "FAKULTAS ILMU DAN TEKNOLOGI KEBUMIAN (FITB) - KAMPUS CIREBON",
            "FAKULTAS TEKNIK MESIN & DIRGANTARA (FTMD)",
            "FAKULTAS TEKNIK SIPIL & LINGKUNGAN (FTSL) - KAMPUS GANESA",
            "FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN (FTSL) - KAMPUS JATINANGOR",
            "FAKULTAS TEKNOLOGI INDUSTRI (FTI) - KAMPUS CIREBON",
            "FAKULTAS TEKNOLOGI INDUSTRI (FTI) - KAMPUS GANESA",
            "FAKULTAS TEKNOLOGI INDUSTRI (FTI) - KAMPUS JATINANGOR",
            "SEK. ARSITEKTUR, PERENC & PENGEMB KEBIJAKAN",
            "SEK. ARSITEKTUR, PERENC & PENGEMB KEBIJAKAN (SAPPK) - KAMPUS CIREBON",
            "SEKOLAH FARMASI (SF)",
            "SEKOLAH ILMU & TEKNO. HAYATI - PROG. SAINS",
            "SEKOLAH ILMU & TEKNO HAYATI - PROG REKAYASA",
            "SEKOLAH TEK. ELEKTRO & INFORMATIKA (STEI)",
        ],
        Soshum: [
            "FAKULTAS SENIRUPA DAN DESAIN (FSRD)",
            "FAKULTAS SENIRUPA DAN DESAIN (FSRD) - KAMPUS CIREBON",
            "SEKOLAH BISNIS DAN MANAJEMEN (SBM)",
        ]
    },
    "UNIVERSITAS PADJADJARAN": {
        Saintek: [
            "AGRIBISNIS",
            "AGROTEKNOLOGI",
            "BIOLOGI",
            "FARMASI",
            "FISIKA",
            "GEOFISIKA",
            "ILMU AKTUARIA",
            "ILMU KELAUTAN",
            "ILMU KEPERAWATAN",
            "ILMU PETERNAKAN",
            "KEDOKTERAN HEWAN",
            "KEPERAWATAN PSDKU PANGANDARAN",
            "KIMIA",
            "MATEMATIKA",
            "PENDIDIKAN DOKTER GIGI",
            "PENDIDIKAN DOKTER",
            "PERIKANAN PSDKU PANGANDARAN",
            "PERIKANAN",
            "PETERNAKAN PSDKU PANGANDARAN",
            "PSIKOLOGI",
            "STATISTIKA",
            "TEKNIK ELEKTRO",
            "TEKNIK GEOLOGI",
            "TEKNIK INFORMATIKA",
            "TEKNIK PERTANIAN",
            "TEKNOLOGI INDUSTRI PERTANIAN",
            "TEKNOLOGI PANGAN",
        ],
        Soshum: [
            "ADMINISTRASI BISNIS PSDKU PANGANDARAN",
            "ADMINISTRASI PUBLIK",
            "AKUNTANSI",
            "ANTROPOLOGI",
            "BISNIS DIGITAL",
            "EKONOMI ISLAM",
            "HUBUNGAN MASYARAKAT",
            "ILMU ADMINISTRASI BISNIS",
            "ILMU EKONOMI",
            "ILMU HUBUNGAN INTERNASIONAL",
            "ILMU HUKUM",
            "ILMU KESEJAHTERAAN SOSIAL",
            "ILMU KOMUNIKASI PSDKU PANGANDARAN",
            "ILMU KOMUNIKASI",
            "ILMU PEMERINTAHAN",
            "ILMU PERPUSTAKAAN",
            "ILMU POLITIK",
            "ILMU SEJARAH",
            "JURNALISTIK",
            "MANAJEMEN",
            "MANAJEMEN KOMUNIKASI",
            "SASTRA ARAB",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
            "SASTRA JEPANG",
            "SASTRA JERMAN",
            "SASTRA PERANCIS",
            "SASTRA RUSIA",
            "SASTRA SUNDA",
            "SOSIOLOGI",
            "TELEVISI DAN FILM",
        ]
    },
    "UNIVERSITAS PENDIDIKAN INDONESIA": {
        Saintek: [],
        Soshum: []
    },
    "ISBI BANDUNG": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ISLAM NEGERI SUNAN GUNUNG DJATI": {
        Saintek: [],
        Soshum: []
    },
    "INSTITUT PERTANIAN BOGOR": {
        Saintek: [
            "AGRIBISNIS",
            "AGRONOMI DAN HORTIKULTURA",
            "AKTUARIA",
            "ARSITEKTUR LANSEKAP",
            "BIOKIMIA",
            "BIOLOGI",
            "BISNIS",
            "EKONOMI PEMBANGUNAN",
            "EKONOMI SUMBERDAYA DAN LINGKUNGAN",
            "EKONOMI SYARIAH",
            "FISIKA",
            "ILMU DAN TEKNOLOGI KELAUTAN",
            "ILMU GIZI",
            "ILMU KELUARGA DAN KONSUMEN",
            "ILMU KOMPUTER",
            "KEDOKTERAN HEWAN",
            "KIMIA",
            "KOMUNIKASI DAN PENGEMBANGAN MASYARAKAT",
            "KONSERVASI SUMBERDAYAHUTAN& EKOWISATA",
            "MANAJEMEN",
            "MANAJEMEN HUTAN",
            "MANAJEMEN SUMBERDAYA LAHAN",
            "MANAJEMEN SUMBERDAYA PERAIRAN",
            "MATEMATIKA",
            "METEOROLOGI TERAPAN",
            "NUTRISI DAN TEKNOLOGI PAKAN",
            "PROTEKSI TANAMAN",
            "SILVIKULTUR",
            "STATISTIKA DAN SAINS DATA",
            "TEKNIK PERTANIAN DAN BIOSISTEM",
            "TEKNIK SIPIL DAN LINGKUNGAN",
            "TEKNOLOGI & MANAJEMEN PERIKANAN BUDIDAYA",
            "TEKNOLOGI & MANAJEMEN PERIKANAN TANGKAP",
            "TEKNOLOGI HASIL HUTAN",
            "TEKNOLOGI HASIL PERAIRAN",
            "TEKNOLOGI HASIL TERNAK",
            "TEKNOLOGI INDUSTRI PERTANIAN",
            "TEKNOLOGI PANGAN",
            "TEKNOLOGI PRODUKSI TERNAK",
        ],
        Soshum: []
    },
    "UNIVERSITAS SILIWANGI": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS JENDERAL SOEDIRMAN": {
        Saintek: [
            "AGRIBISNIS",
            "AGROTEKNOLOGI",
            "AKUAKULTUR",
            "BIOLOGI",
            "FARMASI",
            "FISIKA",
            "ILMU GIZI",
            "ILMU KELAUTAN",
            "INFORMATIKA",
            "KEDOKTERAN GIGI",
            "KEPERAWATAN",
            "KESEHATAN MASYARAKAT",
            "KIMIA",
            "MANAJEMEN SUMBERDAYA PERAIRAN",
            "MATEMATIKA",
            "PENDIDIKAN DOKTER",
            "PENDIDIKAN JASMANI",
            "PETERNAKAN",
            "TEKNIK ELEKTRO",
            "TEKNIK GEOLOGI",
            "TEKNIK INDUSTRI",
            "TEKNIK PERTANIAN",
            "TEKNIK SIPIL",
            "TEKNOLOGI PANGAN",
        ],
        Soshum: [
            "ADMINISTRASI PUBLIK",
            "AKUNTANSI",
            "EKONOMI PEMBANGUNAN",
            "HUBUNGAN INTERNASIONAL",
            "HUKUM",
            "ILMU KOMUNIKASI",
            "ILMU POLITIK",
            "MANAJEMEN",
            "PENDIDIKAN BAHASA INDONESIA",
            "PENDIDIKAN BAHASA INGGRIS",
            "PENDIDIKAN EKONOMI",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
            "SASTRA JEPANG",
            "SOSIOLOGI",
        ]
    },
    "UNIVERSITAS TIDAR": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS SEBELAS MARET": {
        Saintek: [
            "AGRIBISNIS",
            "AGROTEKNOLOGI / AGROEKOTEKNOLOGI",
            "ARSITEKTUR",
            "BIOLOGI",
            "FARMASI",
            "FISIKA",
            "ILMU DAN TEKNOLOGI PANGAN",
            "ILMU LINGKUNGAN",
            "ILMU TANAH",
            "INFORMATIKA",
            "KEDOKTERAN",
            "KESELAMATAN DAN KESEHATAN KERJA",
            "KIMIA",
            "MATEMATIKA",
            "PENDIDIKAN BIOLOGI",
            "PENDIDIKAN FISIKA",
            "PENDIDIKAN IPA",
            "PENDIDIKAN KIMIA",
            "PENDIDIKAN MATEMATIKA",
            "PENDIDIKAN TEKNIK BANGUNAN",
            "PENDIDIKAN TEKNIK INFORMATIKA & KOMPUTER",
            "PENDIDIKAN TEKNIK MESIN",
            "PENGELOLAAN HUTAN",
            "PENYULUHAN DAN KOMUNIKASI PERTANIAN",
            "PERENCANAAN WILAYAH DAN KOTA (PWK)",
            "PETERNAKAN",
            "PSIKOLOGI",
            "STATISTIKA",
            "TEKNIK ELEKTRO",
            "TEKNIK INDUSTRI",
            "TEKNIK KIMIA",
            "TEKNIK MESIN",
            "TEKNIK SIPIL",
        ],
        Soshum: [
            "AKUNTANSI",
            "BIMBINGAN DAN KONSELING",
            "DEMOGRAFI DAN PENCATATAN SIPIL",
            "DESAIN INTERIOR",
            "DESAIN KOMUNIKASI VISUAL",
            "EKONOMI PEMBANGUNAN",
            "HUBUNGAN INTERNASIONAL",
            "ILMU ADMINISTRASI NEGARA",
            "ILMU HUKUM",
            "ILMU KOMUNIKASI",
            "ILMU SEJARAH",
            "KRIYA SENI (DESAIN TEKSTIL)",
            "MANAJEMEN",
            "PEND. BAHASA, SASTRA INDONESIA & DAERAH",
            "PEND. GURU PEND ANAK USIA DINI (PG-PAUD)",
            "PEND. GURU SEKOLAH DASAR (PGSD) KEBUMEN",
            "PEND. GURU SEKOLAH DASAR (PGSD) SURAKARTA",
            "PEND. PANCASILA & KEWARGANEGARAAN (PPKN)",
            "PENDIDIKAN ADMINISTRASI PERKANTORAN",
            "PENDIDIKAN AKUNTANSI",
            "PENDIDIKAN BAHASA INGGRIS",
            "PENDIDIKAN BAHASA JAWA",
            "PENDIDIKAN EKONOMI",
            "PENDIDIKAN GEOGRAFI",
            "PENDIDIKAN JASMANI, KESEHATAN & REKREASI",
            "PENDIDIKAN KEPELATIHAN OLAHRAGA",
            "PENDIDIKAN LUAR BIASA (PENDIDIKAN KHUSUS)",
            "PENDIDIKAN SEJARAH",
            "PENDIDIKAN SENI RUPA",
            "PENDIDIKAN SOSIOLOGI ANTROPOLOGI",
            "SASTRA ARAB",
            "SASTRA DAERAH UNTUK SASTRA JAWA",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
            "SENI RUPA MURNI (LUKIS, GRFS, PTNG, KRMIK)",
            "SOSIOLOGI",
        ]
    },
    "ISI SURAKARTA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS DIPONEGORO": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS NEGERI SEMARANG": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ISLAM NEGERI WALISONGO": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS GADJAH MADA": {
        Saintek: [
            "AGRONOMI",
            "AKUAKULTUR (BUDIDAYA PERIKANAN)",
            "ARSITEKTUR",
            "BIOLOGI",
            "EKONOMI PERTANIAN DAN AGRIBISNIS",
            "ELEKTRONIKA DAN INSTRUMENTASI",
            "FARMASI",
            "FISIKA",
            "GEOFISIKA",
            "GEOGRAFI LINGKUNGAN",
            "GIZI KESEHATAN",
            "HIGIENE GIGI",
            "ILMU AKTUARIA",
            "ILMU DAN INDUSTRI PETERNAKAN",
            "ILMU KEPERAWATAN",
            "ILMU KOMPUTER",
            "ILMU TANAH",
            "KARTOGRAFI DAN PENGINDERAAN JAUH",
            "KEDOKTERAN",
            "KEDOKTERAN GIGI",
            "KEDOKTERAN HEWAN",
            "KEHUTANAN",
            "KIMIA",
            "MANAJEMEN INFORMASI KESEHATAN",
            "MANAJEMEN SUMBERDAYA AKUATIK (MANAJEMEN SUMBER DAYA PERIKANAN)",
            "MATEMATIKA",
            "MIKROBIOLOGI PERTANIAN",
            "PEMBANGUNAN WILAYAH",
            "PENGELOLAAN HUTAN",
            "PENGEMBANGAN PRODUK AGROINDUSTRI",
            "PENYULUHAN DAN KOMUNIKASI PERTANIAN",
            "PERENCANAAN WILAYAH DAN KOTA",
            "PROTEKSI TANAMAN (ILMU HAMA DAN PENYAKIT TUMBUHAN)",
            "SISTEM INFORMASI GEOGRAFIS",
            "STATISTIKA",
            "TEKNIK BIOMEDIS",
            "TEKNIK ELEKTRO",
            "TEKNIK FISIKA",
            "TEKNIK GEODESI",
            "TEKNIK GEOLOGI",
            "TEKNIK INDUSTRI",
            "TEKNIK KIMIA",
            "TEKNIK MESIN",
            "TEKNIK NUKLIR",
            "TEKNIK PENGELOLAAN DAN PEMELIHARAAN INFRASTRUKTUR SIPIL",
            "TEKNIK PENGELOLAAN DAN PERAWATAN ALAT BERAT",
            "TEKNIK PERTANIAN",
            "TEKNIK SIPIL",
            "TEKNOLOGI HASIL PERIKANAN",
            "TEKNOLOGI INDUSTRI PERTANIAN",
            "TEKNOLOGI INFORMASI",
            "TEKNOLOGI PANGAN DAN HASIL PERTANIAN",
            "TEKNOLOGI REKAYASA ELEKTRO",
            "TEKNOLOGI REKAYASA INSTRUMENTASI DAN KONTROL",
            "TEKNOLOGI REKAYASA INTERNET",
            "TEKNOLOGI REKAYASA MESIN",
            "TEKNOLOGI REKAYASA PELAKSANAAN BANGUNAN SIPIL",
            "TEKNOLOGI REKAYASA PERANGKAT LUNAK",
            "TEKNOLOGI SURVEI DAN PEMETAAN DASAR",
            "TEKNOLOGI VETERINER",
        ],
        Soshum: [
            "AKUNTANSI",
            "AKUNTANSI SEKTOR PUBLIK",
            "ANTROPOLOGI BUDAYA",
            "ARKEOLOGI",
            "BAHASA DAN KEBUDAYAAN KOREA",
            "BAHASA DAN SASTRA INDONESIA",
            "BAHASA INGGRIS",
            "BISNIS PERJALANAN WISATA",
            "FILSAFAT",
            "HUKUM",
            "ILMU EKONOMI",
            "ILMU HUBUNGAN INTERNASIONAL",
            "ILMU KOMUNIKASI",
            "MANAJEMEN",
            "MANAJEMEN DAN KEBIJAKAN PUBLIK",
            "MANAJEMEN DAN PENILAIAN PROPERTI",
            "PARIWISATA",
            "PEMBANGUNAN EKONOMI KEWILAYAHAN",
            "PEMBANGUNAN SOSIAL DAN KESEJAHTERAAN",
            "PENGELOLAAN ARSIP DAN REKAMAN INFORMASI",
            "PERBANKAN",
            "POLITIK DAN PEMERINTAHAN",
            "PSIKOLOGI",
            "SASTRA ARAB",
            "SASTRA INGGRIS",
            "SASTRA JAWA",
            "SASTRA JEPANG",
            "SASTRA PRANCIS",
            "SEJARAH",
            "SOSIOLOGI",
        ]
    },
    "UNIVERSITAS NEGERI YOGYAKARTA": {
        Saintek: [],
        Soshum: []
    },
    "UPN \"VETERAN\" YOGYAKARTA": {
        Saintek: [],
        Soshum: []
    },
    "ISI YOGYAKARTA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ISLAM NEGERI SUNAN KALIJAGA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS JEMBER": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS BRAWIJAYA": {
        Saintek: [
            "AGRIBISNIS",
            "AGRIBISNIS (PSDKU KEDIRI)",
            "AGROBISNIS PERIKANAN",
            "AGROEKOTEKNOLOGI",
            "AGROEKOTEKNOLOGI (PSDKU KEDIRI)",
            "AKUAKULTUR (PSDKU KEDIRI)",
            "ARSITEKTUR",
            "BIOLOGI",
            "BIOTEKNOLOGI",
            "BUDIDAYA PERAIRAN",
            "DESAIN GRAFIS",
            "FARMASI",
            "FISIKA",
            "ILMU AKTUARIA",
            "ILMU GIZI",
            "ILMU KELAUTAN",
            "ILMU KEPERAWATAN",
            "INSTRUMENTASI",
            "KEBIDANAN",
            "KEDOKTERAN",
            "KEHUTANAN",
            "KIMIA",
            "MANAJEMEN SUMBERDAYA PERAIRAN",
            "MATEMATIKA",
            "PEMANFAATAN SUMBERDAYA PERIKANAN",
            "PENDIDIKAN DOKTER GIGI",
            "PENDIDIKAN DOKTER HEWAN",
            "PENDIDIKAN TEKNOLOGI INFORMASI",
            "PERENCANAAN WILAYAH & KOTA",
            "PETERNAKAN",
            "PETERNAKAN (PSDKU KEDIRI)",
            "SISTEM INFORMASI",
            "SOSIAL EKONOMI PERIKANAN (PSDKU KEDIRI)",
            "STATISTIKA",
            "TEKNIK ELEKTRO",
            "TEKNIK GEOFISIKA",
            "TEKNIK INDUSTRI",
            "TEKNIK INDUSTRI PERTANIAN",
            "TEKNIK INFORMATIKA",
            "TEKNIK KIMIA",
            "TEKNIK KOMPUTER",
            "TEKNIK LINGKUNGAN",
            "TEKNIK MESIN",
            "TEKNIK PENGAIRAN",
            "TEKNIK PERTANIAN DAN BIOSISTEM",
            "TEKNIK SIPIL",
            "TEKNOLOGI BIOPROSES",
            "TEKNOLOGI HASIL PERIKANAN",
            "TEKNOLOGI INFORMASI",
            "TEKNOLOGI PANGAN",
        ],
        Soshum: [
            "ADMINISTRASI BISNIS",
            "ADMINISTRASI PENDIDIKAN",
            "ADMINISTRASI PUBLIK",
            "AKUNTANSI",
            "ANTROPOLOGI",
            "BAHASA DAN SASTRA PRANCIS",
            "EKONOMI, KEUANGAN DAN PERBANKAN",
            "EKONOMI ISLAM",
            "EKONOMI PEMBANGUNAN",
            "HUBUNGAN INTERNASIONAL",
            "ILMU HUKUM",
            "ILMU KOMUNIKASI",
            "ILMU PEMERINTAHAN",
            "ILMU PERPUSTAKAAN",
            "ILMU POLITIK",
            "KEWIRAUSAHAAN",
            "MANAJEMEN",
            "MANAJEMEN PERHOTELAN",
            "PARIWISATA",
            "PENDIDIKAN BAHASA INGGRIS",
            "PENDIDIKAN BAHASA JEPANG",
            "PENDIDIKAN BHS & SASTRA INDONESIA",
            "PERPAJAKAN",
            "PSIKOLOGI",
            "SASTRA CINA",
            "SASTRA INGGRIS",
            "SASTRA JEPANG",
            "SENI RUPA MURNI",
            "SOSIOLOGI",
        ]
    },
    "UNIVERSITAS NEGERI MALANG": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ISLAM NEGERI MALANG": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS AIRLANGGA": {
        Saintek: [
            "AKUAKULTUR",
            "AKUAKULTUR (PSDKU BANYUWANGI)",
            "BIOLOGI",
            "FARMASI",
            "FISIKA",
            "GIZI",
            "KEBIDANAN",
            "KEDOKTERAN",
            "KEDOKTERAN GIGI",
            "KEDOKTERAN HEWAN",
            "KEDOKTERAN HEWAN (PSDKU BANYUWANGI)",
            "KEPERAWATAN",
            "KESEHATAN MASYARAKAT",
            "KESEHATAN MASYARAKAT (PSDKU BANYUWANGI)",
            "KIMIA",
            "MATEMATIKA",
            "REKAYASA NANOTEKNOLOGI",
            "SISTEM INFORMASI",
            "STATISTIKA",
            "TEKNIK BIOMEDIS",
            "TEKNIK ELEKTRO",
            "TEKNIK INDUSTRI",
            "TEKNIK LINGKUNGAN",
            "TEKNIK ROBOTIKA DAN KECERDASAN BUATAN",
            "TEKNOLOGI HASIL PERIKANAN",
            "TEKNOLOGI SAINS DATA",
        ],
        Soshum: [
            "AKUNTANSI",
            "AKUNTANSI (PSDKU BANYUWANGI)",
            "ANTROPOLOGI",
            "BAHASA DAN SASTRA INDONESIA",
            "BAHASA DAN SASTRA INGGRIS",
            "EKONOMI ISLAM",
            "EKONOMI PEMBANGUNAN",
            "ILMU ADMINISTRASI NEGARA",
            "ILMU HUBUNGAN INTERNASIONAL",
            "ILMU HUKUM",
            "ILMU INFORMASI DAN PERPUSTAKAAN",
            "ILMU KOMUNIKASI",
            "ILMU POLITIK",
            "ILMU SEJARAH",
            "MANAJEMEN",
            "PSIKOLOGI",
            "SOSIOLOGI",
            "STUDI KEJEPANGAN",
        ]
    },
    "INSTITUT TEKNOLOGI SEPULUH NOPEMBER": {
        Saintek: [
            "ARSITEKTUR",
            "BIOLOGI",
            "DESAIN INTERIOR",
            "DESAIN KOMUNIKASI VISUAL",
            "DESAIN PRODUK INDUSTRI",
            "FISIKA",
            "KIMIA",
            "MATEMATIKA",
            "PERENCANAAN WILAYAH DAN KOTA",
            "SAINS AKTUARIA",
            "SISTEM INFORMASI",
            "STATISTIKA",
            "STATISTIKA BISNIS",
            "TEK. SIST PERKAPALAN (GLR GANDA ITS-JERMAN)",
            "TEKNIK BIOMEDIK",
            "TEKNIK ELEKTRO",
            "TEKNIK FISIKA",
            "TEKNIK GEOFISIKA",
            "TEKNIK GEOMATIKA",
            "TEKNIK INDUSTRI",
            "TEKNIK INFORMATIKA",
            "TEKNIK KELAUTAN",
            "TEKNIK KIMIA",
            "TEKNIK KOMPUTER",
            "TEKNIK LINGKUNGAN",
            "TEKNIK MATERIAL",
            "TEKNIK MESIN",
            "TEKNIK PERKAPALAN",
            "TEKNIK SIPIL",
            "TEKNIK SIPIL",
            "TEKNIK SISTEM PERKAPALAN",
            "TEKNIK TRANSPORTASI LAUT",
            "TEKNOLOGI INFORMASI",
            "TEKNOLOGI REKAYASA INSTRUMENTASI",
            "TEKNOLOGI REKAYASA KIMIA INDUSTRI",
            "TEKNOLOGI REKAYASA KONSTRUKSI BANGUNAN AIR",
            "TEKNOLOGI REKAYASA KONVERSI ENERGI",
            "TEKNOLOGI REKAYASA MANUFAKTUR",
            "TEKNOLOGI REKAYASA OTOMASI",
        ],
        Soshum: [
            "MANAJEMEN BISNIS",
            "STUDI PEMBANGUNAN"
        ]
    },
    "UNIVERSITAS NEGERI SURABAYA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS TRUNOJOYO MADURA": {
        Saintek: [],
        Soshum: []
    },
    "UPN \"VETERAN\" JAWA TIMUR": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS ISLAM NEGERI SUNAN AMPEL SURABAYA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS TANJUNGPURA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS PALANGKARAYA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS LAMBUNG MANGKURAT": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS MULAWARMAN": {
        Saintek: [
            "AGRIBISNIS",
            "AGROEKOTEKNOLOGI",
            "AKUAKULTUR",
            "ARSITEKTUR",
            "BIOLOGI",
            "FARMASI",
            "FARMASI KLINIS",
            "FISIKA",
            "GEOFISIKA",
            "ILMU KELAUTAN",
            "INFORMATIKA",
            "KEDOKTERAN GIGI",
            "KEHUTANAN",
            "KESEHATAN MASYARAKAT",
            "KIMIA",
            "MATEMATIKA",
            "PENDIDIKAN BIOLOGI",
            "PENDIDIKAN DOKTER",
            "PENDIDIKAN FISIKA",
            "PENDIDIKAN KIMIA",
            "PENDIDIKAN KOMPUTER",
            "PENDIDIKAN MATEMATIKA",
            "PENGELOLAAN SUMBERDAYA PERIKANAN",
            "PETERNAKAN",
            "SISTEM INFORMASI",
            "SOSIAL EKONOMI PERIKANAN",
            "STATISTIKA",
            "TEKNIK ELEKTRO",
            "TEKNIK GEOLOGI",
            "TEKNIK INDUSTRI",
            "TEKNIK KIMIA",
            "TEKNIK LINGKUNGAN",
            "TEKNIK PERTAMBANGAN",
            "TEKNIK SIPIL",
            "TEKNOLOGI HASIL PERIKANAN",
            "TEKNOLOGI HASIL PERTANIAN",
        ],
        Soshum: [
            "ADMINISTRASI BISNIS",
            "ADMINISTRASI PUBLIK",
            "AKUNTANSI",
            "BIMBINGAN DAN KONSELING",
            "EKONOMI PEMBANGUNAN",
            "EKONOMI SYARIAH",
            "ETNOMUSIKOLOGI",
            "HUKUM",
            "ILMU HUBUNGAN INTERNASIONAL",
            "ILMU KOMUNIKASI",
            "ILMU PEMERINTAHAN",
            "MANAJEMEN",
            "PEMBANGUNAN SOSIAL",
            "PEND. BAHASA, SASTRA INDO. & DAERAH",
            "PEND. PANCASILA DAN KEWARGANEGARAAN",
            "PENDIDIKAN ANAK USIA DINI",
            "PENDIDIKAN BAHASA INGGRIS",
            "PENDIDIKAN EKONOMI",
            "PENDIDIKAN GEOGRAFI",
            "PENDIDIKAN GURU SEKOLAH DASAR",
            "PENDIDIKAN JASMANI",
            "PENDIDIKAN MASYARAKAT",
            "PENDIDIKAN SEJARAH",
            "PSIKOLOGI",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
        ]
    },
    "INSTITUT TEKNOLOGI KALIMANTAN": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS BORNEO TARAKAN": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS UDAYANA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS PENDIDIKAN GANESHA": {
        Saintek: [],
        Soshum: []
    },
    "ISI DENPASAR": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS MATARAM": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS NUSA CENDANA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS TIMOR": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS HASANUDDIN": {
        Saintek: [
            "AGRIBISNIS",
            "AGROTEKNOLOGI",
            "BIOLOGI",
            "BUDIDAYA PERAIRAN",
            "FARMASI",
            "FISIKA",
            "FISOTERAPI",
            "GEOFISIKA",
            "ILMU AKTUARIA",
            "ILMU DAN TEKNOLOGI PANGAN",
            "ILMU GIZI",
            "ILMU KELAUTAN",
            "ILMU KEPERAWATAN",
            "ILMU KOMPUTER",
            "ILMU TANAH",
            "KEDOKTERAN HEWAN",
            "KEHUTANAN",
            "KESEHATAN MASYARAKAT",
            "KETEKNIKAN PERTANIAN",
            "KIMIA",
            "KONSERVASI HUTAN",
            "MANAJEMEN SUMBERDAYA PERAIRAN",
            "MATEMATIKA",
            "PEMANFAATAN SUMBERDAYA PERIKANAN",
            "PENDIDIKAN DOKTER GIGI",
            "PENDIDIKAN DOKTER",
            "PETERNAKAN",
            "PROTEKSI TANAMAN",
            "PSIKOLOGI",
            "REKAYASA KEHUTANAN",
            "SOSIAL EKONOMI PERIKANAN",
            "STATISTIKA",
            "TEKNIK ARSITEKTUR",
            "TEKNIK ELEKTRO",
            "TEKNIK GEOLOGI",
            "TEKNIK INDUSTRI",
            "TEKNIK INFORMATIKA",
            "TEKNIK KELAUTAN",
            "TEKNIK LINGKUNGAN",
            "TEKNIK MESIN",
            "TEKNIK PENGEMB. WILAYAH KOTA",
            "TEKNIK PERKAPALAN",
            "TEKNIK PERTAMBANGAN",
            "TEKNIK SIPIL",
            "TEKNIK SISTEM PERKAPALAN",
            "TEKNOLOGI HASIL PERIKANAN",
            "TEKNOLOGI PRODUKSI TANAMAN PANGAN",
        ],
        Soshum: [
            "ADMINISTRASI PUBLIK",
            "AKUNTANSI",
            "ANTROPOLOGI SOSIAL",
            "ARKEOLOGI",
            "BAHASA MANDARIN DAN KEBUDAYAAN TIONGKOK",
            "EKONOMI PEMBANGUNAN",
            "HUKUM ADMINISTRASI NEGARA",
            "ILMU HUBUNGAN INTERNASIONAL",
            "ILMU HUKUM",
            "ILMU KOMUNIKASI",
            "ILMU PEMERINTAHAN",
            "ILMU POLITIK",
            "ILMU SEJARAH",
            "MANAJEMEN",
            "SASTRA ASIA BARAT/ARAB",
            "SASTRA DAERAH/BUGIS MAKASSAR",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
            "SASTRA JEPANG",
            "SASTRA PERANCIS/ BARAT ROMAN",
            "SOSIOLOGI",
        ]
    },
    "UNIVERSITAS NEGERI MAKASSAR": {
        Saintek: [
            "ADMINISTRASI KESEHATAN",
            "ARSITEKTUR",
            "BIOLOGI",
            "DESAIN KOMUNIKASI VISUAL",
            "FISIKA",
            "GEOGRAFI",
            "GIZI",
            "ILMU KEOLAHRAGAAN",
            "KIMIA",
            "MATEMATIKA",
            "MESIN OTOMOTIF",
            "PEND. BIOLOGI KLS INTERNASIONAL (BILINGUAL)",
            "PEND. FISIKA KLS INTERNASIONAL (BILINGUAL)",
            "PEND. KIMIA KLS INTERNASIONAL (BILINGUAL)",
            "PEND. MATEMATIKA KLS INTERNAS. (BILINGUAL)",
            "PEND. TEKNIK ELEKTRONIKA",
            "PEND. TEKNIK OTOMOTIF",
            "PENDIDIKAN BIOLOGI",
            "PENDIDIKAN FISIKA",
            "PENDIDIKAN IPA KLS INTERNASIONAL (BILINGUAL)",
            "PENDIDIKAN IPA",
            "PENDIDIKAN KIMIA",
            "PENDIDIKAN MATEMATIKA",
            "PENDIDIKAN TEKNIK BANGUNAN",
            "PENDIDIKAN TEKNIK ELEKTRO",
            "PENDIDIKAN TEKNIK INFORMATIKA & KOMPUTER",
            "PENDIDIKAN TEKNIK MESIN",
            "PENDIDIKAN TEKNOLOGI PERTANIAN",
            "PENDIDIKAN VOKASIONAL MEKATRONIKA",
            "STATISTIKA",
            "TEKNIK ELEKTRO",
            "TEKNIK ELEKTRONIKA",
            "TEKNIK KOMPUTER",
            "TEKNIK MESIN",
            "TEKNIK SIPIL BANGUNAN GEDUNG",
        ],
        Soshum: [
            "ADMINISTRASI NEGARA",
            "ADMINISTRASI PENDIDIKAN",
            "AKUNTANSI",
            "AKUNTANSI",
            "BAHASA INGGRIS",
            "BIMBINGAN DAN KONSELING",
            "BISNIS DIGITAL",
            "EKONOMI PEMBANGUNAN",
            "ILMU ADMINISTRASI BISNIS",
            "KEWIRAUSAHAAN",
            "MANAJEMEN",
            "P. GURU SEK DASAR BILINGUAL (KAMP MAKASSAR)",
            "PEND. ADMINISTRASI PERKANTORAN",
            "PEND. AKUNTANSI",
            "PEND. GEOGRAFI KLS INTERNAS. (BILINGUAL)",
            "PEND. GURU SEK. DASAR (KAMPUS MAKASSAR)",
            "PEND. GURU SEK. DASAR (KAMPUS PARE-PARE)",
            "PEND. GURU SEKOLAH DASAR (KAMPUS BONE)",
            "PENDIDIKAAN SOSIOLOGI",
            "PENDIDIKAN ANTROPOLOGI",
            "PENDIDIKAN BAHASA ARAB",
            "PENDIDIKAN BAHASA DAN SASTRA DAERAH",
            "PENDIDIKAN BAHASA DAN SASTRA INDONESIA",
            "PENDIDIKAN BAHASA INGGRIS",
            "PENDIDIKAN BAHASA JERMAN",
            "PENDIDIKAN BAHASA MANDARIN",
            "PENDIDIKAN EKONOMI",
            "PENDIDIKAN GEOGRAFI",
            "PENDIDIKAN GURU PAUD",
            "PENDIDIKAN IPS",
            "PENDIDIKAN JASMANI, KESEHATAN & REKREASI",
            "PENDIDIKAN KEPELATIHAN OLAHRAGA",
            "PENDIDIKAN KESEJAHTERAAN KELUARGA",
            "PENDIDIKAN LUAR BIASA",
            "PENDIDIKAN LUAR SEKOLAH",
            "PENDIDIKAN PANCASILA DAN KEWARGANEGARAAN",
            "PENDIDIKAN SEJARAH",
            "PENDIDIKAN SENI DRAMA, TARI, DAN MUSIK",
            "PENDIDIKAN SENI RUPA",
            "PSIKOLOGI",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
            "SENI TARI",
            "SOSIOLOGI",
            "TATA BOGA",
            "TEKNOLOGI PENDIDIKAN",
        ]
    },
    "UNIVERSITAS ISLAM NEGERI ALAUDDIN": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS SAM RATULANGI": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS NEGERI MANADO": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS TADULAKO": {
        Saintek: [
            "AGRIBISNIS",
            "AGROTEKNOLOGI",
            "AGROTEKNOLOGI (PSDKU MOROWALI)",
            "AGROTEKNOLOGI (PSDKU TOUNA)",
            "BIOLOGI",
            "BUDIDAYA PERAIRAN",
            "FARMASI",
            "FISIKA",
            "GIZI",
            "KEHUTANAN",
            "KESEHATAN MASYARAKAT",
            "KIMIA",
            "MATEMATIKA",
            "PEND. BIOLOGI",
            "PEND. DOKTER",
            "PEND. FISIKA",
            "PEND. KIMIA",
            "PEND. MATEMATIKA",
            "PERENCANAAN WILAYAH DAN KOTA",
            "PETERNAKAN",
            "SISTEM INFORMASI",
            "STATISTIKA",
            "TEKNIK ARSITEKTUR",
            "TEKNIK ELEKTRO",
            "TEKNIK GEO FISIKA",
            "TEKNIK GEOLOGI",
            "TEKNIK INFORMATIKA",
            "TEKNIK LINGKUNGAN",
            "TEKNIK MESIN",
            "TEKNIK SIPIL",
            "TEKNIK SIPIL (PSDKU MOROWALI)",
            "TEKNIK SIPIL (PSDKU TOUNA)",
        ],
        Soshum: [
            "ADMINSTRASI NEGARA",
            "ANTROPOLOGI",
            "BIMBINGAN DAN KONSELING",
            "EKONOMI AKUNTANSI",
            "EKONOMI MANAJEMEN",
            "EKONOMI PEMBANGUNAN",
            "ILMU HUKUM",
            "ILMU KOMUNIKASI",
            "ILMU PEMERINTAHAN",
            "MANAJEMEN (PSDKU MOROWALI)",
            "MANAJEMEN (PSDKU TOUNA)",
            "PEND. BAHASA INDONESIA",
            "PEND. BAHASA INGGRIS",
            "PEND. GEOGRAFI",
            "PEND. GURU PAUD",
            "PEND. GURU SEKOLAH DASAR",
            "PEND. JASMANI, KESEHATAN DAN REKREASI",
            "PEND. PANCASILA DAN KEWARGANEGARAAN",
            "PEND. SEJARAH",
            "SOSIOLOGI",
        ]
    },
    "UNIVERSITAS SULAWESI BARAT": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS HALUOLEO": {
        Saintek: [
            "AGRIBISNIS",
            "AGROBISNIS PERIKANAN",
            "AGROTEKNOLOGI / AGROEKOTEKNOLOGI",
            "BIOLOGI",
            "BIOTEKNOLOGI",
            "BUDIDAYA PERAIRAN",
            "FARMASI",
            "FISIKA",
            "GEOGRAFI",
            "GIZI",
            "ILMU DAN TEKNOLOGI PANGAN",
            "ILMU KELAUTAN",
            "ILMU KEOLAHRAGAAN",
            "ILMU KESEHATAN MASYARAKAT",
            "ILMU KOMPUTER",
            "ILMU LINGKUNGAN",
            "ILMU TANAH",
            "KEHUTANAN",
            "KIMIA",
            "MANAJEMEN SUMBERDAYA PERAIRAN",
            "MATEMATIKA",
            "OSEANOGRAFI",
            "PENDIDIKAN BIOLOGI",
            "PENDIDIKAN DOKTER",
            "PENDIDIKAN FISIKA",
            "PENDIDIKAN KIMIA",
            "PENDIDIKAN MATEMATIKA",
            "PENDIDIKAN VOKASIONAL TEKNIK",
            "PENYULUHAN PERTANIAN",
            "PERIKANAN TANGKAP",
            "PETERNAKAN",
            "PROTEKSI TANAMAN",
            "REKAYASA INFRASTRUKTUR DAN LINGKUNGAN",
            "STATISTIKA",
            "TEKNIK ARSITEKTUR",
            "TEKNIK ELEKTRO",
            "TEKNIK GEOFISIKA",
            "TEKNIK GEOLOGI",
            "TEKNIK INFORMATIKA",
            "TEKNIK KELAUTAN",
            "TEKNIK MESIN",
            "TEKNIK PERTAMBANGAN",
            "TEKNIK SIPIL",
            "TEKNOLOGI HASIL PERIKANAN",
        ],
        Soshum: [
            "ADMINISTRASI BISNIS",
            "AKUTANSI",
            "ANTROPOLOGI SOSIAL",
            "ARKEOLOGI",
            "EKONOMI PEMBANGUNAN",
            "ILMU ADMINISTRASI NEGARA",
            "ILMU HUKUM",
            "ILMU KESEJAHTERAAN SOSIAL",
            "ILMU KOMUNIKASI",
            "ILMU PEMERINTAHAN",
            "ILMU POLITIK",
            "ILMU SEJARAH",
            "JURNALISTIK",
            "MANAJEMEN",
            "PEND. BAHASA, SASTRA INDO. & DAERAH",
            "PEND. GURU SEKOLAH DASAR (PGSD) S1",
            "PEND. JASMANI, KESEHATAN DAN REKREASI",
            "PEND. PANCASILA & KEWARGANEGARAAN",
            "PENDIDIKAN AKUNTANSI",
            "PENDIDIKAN ANAK USIA DINI (PG-PAUD)",
            "PENDIDIKAN BAHASA INGGRIS",
            "PENDIDIKAN BIMBINGAN DAN KONSELING",
            "PENDIDIKAN EKONOMI",
            "PENDIDIKAN GEOGRAFI",
            "PENDIDIKAN SEJARAH",
            "PERPUSTAKAAN DAN ILMU INFORMASI",
            "PSIKOLOGI",
            "SASTRA INDONESIA",
            "SASTRA INGGRIS",
            "SASTRA PRANCIS",
            "SOSIOLOGI",
            "TRADISI LISAN",
        ]
    },
    "UNIVERSITAS NEGERI GORONTALO": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS SEMBILAN BELAS NOVEMBER KOLAKA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS PATTIMURA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS KHAIRUN": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS CENDERAWASIH": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS MUSAMUS MERAUKE": {
        Saintek: [],
        Soshum: []
    },
    "ISBI TANAH PAPUA": {
        Saintek: [],
        Soshum: []
    },
    "UNIVERSITAS PAPUA": {
        Saintek: [],
        Soshum: []
    },
}